### ISSUE TITLE
Vulnerability report process

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/meta#10]
# OpenSSF Best Practices Badge Program

### Vulnerability report process

- [ ] The project MUST publish the process for reporting vulnerabilities on the project site. {Met URL} [[vulnerability_report_process](https://www.bestpractices.dev/en/criteria/0#0.vulnerability_report_process)]
- [ ] If private vulnerability reports are supported, the project MUST include how to send the information in a way that is kept private. {N/A allowed} {Met URL} [[vulnerability_report_private](https://www.bestpractices.dev/en/criteria/0#0.vulnerability_report_private)]
- [ ] The project's initial response time for any vulnerability report received in the last 6 months MUST be less than or equal to 14 days. {N/A allowed} [[vulnerability_report_response](https://www.bestpractices.dev/en/criteria/0#0.vulnerability_report_response)]
