### ISSUE TITLE
Working build system

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/meta#11]
# OpenSSF Best Practices Badge Program

### Working build system

- [ ] If the software produced by the project requires building for use, the project MUST provide a working build system that can automatically rebuild the software from source code. {N/A allowed} [[build](https://www.bestpractices.dev/en/criteria/0#0.build)]
- [ ] It is SUGGESTED that common tools be used for building the software. {N/A allowed} [[build_common_tools](https://www.bestpractices.dev/en/criteria/0#0.build_common_tools)]
- [ ] The project SHOULD be buildable using only FLOSS tools. {N/A allowed} [[build_floss_tools](https://www.bestpractices.dev/en/criteria/0#0.build_floss_tools)]
