### ISSUE TITLE
Automated test suite

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/meta#12]
# OpenSSF Best Practices Badge Program

### Automated test suite

- [ ] The project MUST use at least one automated test suite that is publicly released as FLOSS (this test suite may be maintained as a separate FLOSS project). The project MUST clearly show or document how to run the test suite(s) (e.g., via a continuous integration (CI) script or via documentation in files such as BUILD.md, README.md, or CONTRIBUTING.md). [[test](https://www.bestpractices.dev/en/criteria/0#0.test)]
- [ ] A test suite SHOULD be invocable in a standard way for that language. [[test_invocation](https://www.bestpractices.dev/en/criteria/0#0.test_invocation)]
- [ ] It is SUGGESTED that the test suite cover most (or ideally all) the code branches, input fields, and functionality. [[test_most](https://www.bestpractices.dev/en/criteria/0#0.test_most)]
- [ ] It is SUGGESTED that the project implement continuous integration (where new or changed code is frequently integrated into a central code repository and automated tests are run on the result). [[test_continuous_integration](https://www.bestpractices.dev/en/criteria/0#0.test_continuous_integration)]
