### ISSUE TITLE
New functionality testing

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/meta#13]
# OpenSSF Best Practices Badge Program

### New functionality testing

- [ ] The project MUST have a general policy (formal or not) that as major new functionality is added to the software produced by the project, tests of that functionality should be added to an automated test suite. [[test_policy](https://www.bestpractices.dev/en/criteria/0#0.test_policy)]
- [ ] The project MUST have evidence that the [test_policy](https://www.bestpractices.dev/en/criteria/0#test_policy) for adding tests has been adhered to in the most recent major changes to the software produced by the project. [[tests_are_added](https://www.bestpractices.dev/en/criteria/0#0.tests_are_added)]
- [ ] It is SUGGESTED that this policy on adding tests (see [test_policy](https://www.bestpractices.dev/en/criteria/0#test_policy)) be documented in the instructions for change proposals. [[tests_documented_added](https://www.bestpractices.dev/en/criteria/0#0.tests_documented_added)]
