### ISSUE TITLE
Warning flags

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/meta#14]
# OpenSSF Best Practices Badge Program

### Warning flags

- [ ] The project MUST enable one or more compiler warning flags, a "safe" language mode, or use a separate "linter" tool to look for code quality errors or common simple mistakes, if there is at least one FLOSS tool that can implement this criterion in the selected language. {N/A allowed} [[warnings](https://www.bestpractices.dev/en/criteria/0#0.warnings)]
- [ ] The project MUST address warnings. {N/A allowed} [[warnings_fixed](https://www.bestpractices.dev/en/criteria/0#0.warnings_fixed)]
- [ ] It is SUGGESTED that projects be maximally strict with warnings in the software produced by the project, where practical. {N/A allowed} [[warnings_strict](https://www.bestpractices.dev/en/criteria/0#0.warnings_strict)]
