### ISSUE TITLE
Basic project website content

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/meta#2]
# OpenSSF Best Practices Badge Program

### Basic project website content

- [ ] The project website MUST succinctly describe what the software does (what problem does it solve?). [[description_good](https://www.bestpractices.dev/en/criteria/0#0.description_good)]
- [ ] The project website MUST provide information on how to: obtain, provide feedback (as bug reports or enhancements), and contribute to the software. [[interact](https://www.bestpractices.dev/en/criteria/0#0.interact)]
- [ ] The information on how to contribute MUST explain the contribution process (e.g., are pull requests used?) {Met URL} [[contribution](https://www.bestpractices.dev/en/criteria/0#0.contribution)]
- [ ] The information on how to contribute SHOULD include the requirements for acceptable contributions (e.g., a reference to any required coding standard). {Met URL} [[contribution_requirements](https://www.bestpractices.dev/en/criteria/0#0.contribution_requirements)]
