### ISSUE TITLE
Static code analysis

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/meta#20]
# OpenSSF Best Practices Badge Program

### Static code analysis

- [ ] At least one static code analysis tool (beyond compiler warnings and "safe" language modes) MUST be applied to any proposed major production release of the software before its release, if there is at least one FLOSS tool that implements this criterion in the selected language. {N/A justification} {Met justification} [[static_analysis](https://www.bestpractices.dev/en/criteria/0#0.static_analysis)]
- [ ] It is SUGGESTED that at least one of the static analysis tools used for the static_analysis criterion include rules or approaches to look for common vulnerabilities in the analyzed language or environment. {N/A allowed} [[static_analysis_common_vulnerabilities](https://www.bestpractices.dev/en/criteria/0#0.static_analysis_common_vulnerabilities)]
- [ ] All medium and higher severity exploitable vulnerabilities discovered with static code analysis MUST be fixed in a timely way after they are confirmed. {N/A allowed} [[static_analysis_fixed](https://www.bestpractices.dev/en/criteria/0#0.static_analysis_fixed)]
- [ ] It is SUGGESTED that static source code analysis occur on every commit or at least daily. {N/A allowed} [[static_analysis_often](https://www.bestpractices.dev/en/criteria/0#0.static_analysis_often)]
