### ISSUE TITLE
Dynamic code analysis

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/meta#21]
# OpenSSF Best Practices Badge Program

### Dynamic code analysis

- [ ] It is SUGGESTED that at least one dynamic analysis tool be applied to any proposed major production release of the software before its release. [[dynamic_analysis](https://www.bestpractices.dev/en/criteria/0#0.dynamic_analysis)]
- [ ] It is SUGGESTED that if the software produced by the project includes software written using a memory-unsafe language (e.g., C or C++), then at least one dynamic tool (e.g., a fuzzer or web application scanner) be routinely used in combination with a mechanism to detect memory safety problems such as buffer overwrites. If the project does not produce software written in a memory-unsafe language, choose "not applicable" (N/A). {N/A allowed} [[dynamic_analysis_unsafe](https://www.bestpractices.dev/en/criteria/0#0.dynamic_analysis_unsafe)]
- [ ] It is SUGGESTED that the project use a configuration for at least some dynamic analysis (such as testing or fuzzing) which enables many assertions. In many cases these assertions should not be enabled in production builds. [[dynamic_analysis_enable_assertions](https://www.bestpractices.dev/en/criteria/0#0.dynamic_analysis_enable_assertions)]
- [ ] All medium and higher severity exploitable vulnerabilities discovered with dynamic code analysis MUST be fixed in a timely way after they are confirmed. {N/A allowed} [[dynamic_analysis_fixed](https://www.bestpractices.dev/en/criteria/0#0.dynamic_analysis_fixed)]
