### ISSUE TITLE
FLOSS license

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/meta#3]
# OpenSSF Best Practices Badge Program

### FLOSS license

- [ ] The software produced by the project MUST be released as FLOSS. [[floss_license](https://www.bestpractices.dev/en/criteria/0#0.floss_license)]
- [ ] It is SUGGESTED that any required license(s) for the software produced by the project be [approved by the Open Source Initiative (OSI).](https://opensource.org/licenses) [[floss_license_osi](https://www.bestpractices.dev/en/criteria/0#0.floss_license_osi)]
- [ ] The project MUST post the license(s) of its results in a standard location in their source repository. {Met URL} [[license_location](https://www.bestpractices.dev/en/criteria/0#0.license_location)]
