### ISSUE TITLE
Other

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/meta#5]
# OpenSSF Best Practices Badge Program

### Other

- [ ] The project sites (website, repository, and download URLs) MUST support HTTPS using TLS. [[sites_https](https://www.bestpractices.dev/en/criteria/0#0.sites_https)]
- [ ] The project MUST have one or more mechanisms for discussion (including proposed changes and issues) that are searchable, allow messages and topics to be addressed by URL, enable new people to participate in some of the discussions, and do not require client-side installation of proprietary software. [[discussion](https://www.bestpractices.dev/en/criteria/0#0.discussion)]
- [ ] The project SHOULD provide documentation in English and be able to accept bug reports and comments about code in English. [[english](https://www.bestpractices.dev/en/criteria/0#0.english)]
- [ ] The project MUST be maintained. [[maintained](https://www.bestpractices.dev/en/criteria/0#0.maintained)]
