### ISSUE TITLE
Public version-controlled source repository

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/meta#6]
# OpenSSF Best Practices Badge Program

### Public version-controlled source repository

- [ ] The project MUST have a version-controlled source repository that is publicly readable and has a URL. [[repo_public](https://www.bestpractices.dev/en/criteria/0#0.repo_public)]
- [ ] The project's source repository MUST track what changes were made, who made the changes, and when the changes were made. [[repo_track](https://www.bestpractices.dev/en/criteria/0#0.repo_track)]
- [ ] To enable collaborative review, the project's source repository MUST include interim versions for review between releases; it MUST NOT include only final releases. [[repo_interim](https://www.bestpractices.dev/en/criteria/0#0.repo_interim)]
- [ ] It is SUGGESTED that common distributed version control software be used (e.g., git) for the project's source repository. [[repo_distributed](https://www.bestpractices.dev/en/criteria/0#0.repo_distributed)]
