### ISSUE TITLE
Unique version numbering

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/meta#7]
# OpenSSF Best Practices Badge Program

### Unique version numbering

- [ ] The project results MUST have a unique version identifier for each release intended to be used by users. [[version_unique](https://www.bestpractices.dev/en/criteria/0#0.version_unique)]
- [ ] It is SUGGESTED that the [Semantic Versioning (SemVer)](https://semver.org/) or [Calendar Versioning (CalVer)](https://calver.org/) version numbering format be used for releases. It is SUGGESTED that those who use CalVer include a micro level value. [[version_semver](https://www.bestpractices.dev/en/criteria/0#0.version_semver)]
- [ ] It is SUGGESTED that projects identify each release within their version control system. For example, it is SUGGESTED that those using git identify each release using git tags. [[version_tags](https://www.bestpractices.dev/en/criteria/0#0.version_tags)]
