### ISSUE TITLE
Bug-reporting process

### ISSUE THREAD

**Issue by aschaeffer** [reactive-graph/meta#9]
# OpenSSF Best Practices Badge Program

### Bug-reporting process

- [ ] The project MUST provide a process for users to submit bug reports (e.g., using an issue tracker or a mailing list). {Met URL} [[report_process](https://www.bestpractices.dev/en/criteria/0#0.report_process)]
- [ ] The project SHOULD use an issue tracker for tracking individual issues. [[report_tracker](https://www.bestpractices.dev/en/criteria/0#0.report_tracker)]
- [ ] The project MUST acknowledge a majority of bug reports submitted in the last 2-12 months (inclusive); the response need not include a fix. [[report_responses](https://www.bestpractices.dev/en/criteria/0#0.report_responses)]
- [ ] The project SHOULD respond to a majority (>50%) of enhancement requests in the last 2-12 months (inclusive). [[enhancement_responses](https://www.bestpractices.dev/en/criteria/0#0.enhancement_responses)]
- [ ] The project MUST have a publicly available archive for reports and responses for later searching. {Met URL} [[report_archive](https://www.bestpractices.dev/en/criteria/0#0.report_archive)]
